FROM oven/bun:1 AS builder
WORKDIR /app
COPY package.json bun.lock* ./
RUN bun install --frozen-lockfile
COPY . .
ARG SERVICE_NAME
RUN bunx nest build ${SERVICE_NAME}

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=builder /app/dist/apps/${SERVICE_NAME} ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
ARG SERVICE_NAME
ENV SERVICE_NAME=${SERVICE_NAME}
CMD ["node", "dist/main.js"]
