FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN npx nest build prescription

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=builder /app/dist/apps/prescription ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
CMD ["node", "dist/main.js"]
