FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
ARG SERVICE_NAME
RUN npm run build ${SERVICE_NAME}

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=builder /app/dist/apps/${SERVICE_NAME} ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
ARG SERVICE_NAME
ENV SERVICE_NAME=${SERVICE_NAME}
CMD ["node", "dist/main.js"]
